CREATE TABLE IF NOT EXISTS schema_version (version INTEGER PRIMARY KEY);
INSERT INTO schema_version(version) VALUES (1) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS research_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source TEXT NOT NULL, external_id TEXT NOT NULL, title TEXT NOT NULL,
 canonical_url TEXT NOT NULL, excerpt TEXT NOT NULL, fingerprint TEXT NOT NULL UNIQUE,
 author TEXT, published_at TEXT, discovered_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new',
 summary TEXT, category TEXT, confidence DOUBLE PRECISION, UNIQUE(source, external_id)
);
CREATE TABLE IF NOT EXISTS evidence_records (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, research_item_id BIGINT NOT NULL REFERENCES research_items(id),
 source_url TEXT NOT NULL, excerpt TEXT NOT NULL, content_hash TEXT NOT NULL,
 captured_at TEXT NOT NULL, evidence_type TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS drafts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, text TEXT NOT NULL, category TEXT NOT NULL, status TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 1, confidence DOUBLE PRECISION NOT NULL, factual_risk TEXT NOT NULL,
 verification_status TEXT NOT NULL, research_item_id BIGINT NOT NULL REFERENCES research_items(id),
 provider TEXT NOT NULL, model TEXT NOT NULL, prompt_version TEXT NOT NULL,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, rejection_reason TEXT
);
CREATE TABLE IF NOT EXISTS claims (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, draft_id BIGINT NOT NULL REFERENCES drafts(id), claim_index INTEGER NOT NULL,
 text TEXT NOT NULL, kind TEXT NOT NULL, evidence_ids TEXT NOT NULL, supported BOOLEAN, note TEXT
);
CREATE TABLE IF NOT EXISTS draft_revisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, draft_id BIGINT NOT NULL REFERENCES drafts(id), revision INTEGER NOT NULL,
 text TEXT NOT NULL, verification_status TEXT NOT NULL, changed_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS pipeline_runs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL,
 finished_at TEXT, detail TEXT
);
CREATE TABLE IF NOT EXISTS model_calls (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id BIGINT REFERENCES pipeline_runs(id), role TEXT NOT NULL,
 provider TEXT NOT NULL, model TEXT NOT NULL, response_id TEXT, input_tokens INTEGER,
 output_tokens INTEGER, prompt_version TEXT NOT NULL, created_at TEXT NOT NULL
);
