CREATE TABLE research_claims (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 research_item_id BIGINT NOT NULL REFERENCES research_items(id),
 claim_index INTEGER NOT NULL,
 text TEXT NOT NULL,
 kind TEXT NOT NULL,
 evidence_ids TEXT NOT NULL,
 UNIQUE(research_item_id, claim_index)
);
INSERT INTO schema_version(version) VALUES (3) ON CONFLICT DO NOTHING;
