'use strict';
let config, token, previewId, report;
const $ = id => document.getElementById(id);
const text = (tag, value) => {const node = document.createElement(tag);node.textContent = value;return node;};
function status(value, error=false){$('status').textContent=value;$('status').classList.toggle('error',error);}
async function api(path, payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':token},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'İstek başarısız');return data;}
function invalidate() { previewId=null; $('save').disabled=true; }
function fillRoles(roles){$('roles').replaceChildren();for(const [role,values] of Object.entries(roles)){const row=document.createElement('tr');row.dataset.role=role;row.append(text('td',role));const model=document.createElement('input');model.value=values.model;model.required=true;model.setAttribute('aria-label',role+' modeli');model.maxLength=128;const effort=document.createElement('select');effort.setAttribute('aria-label',role+' reasoning');for(const e of config.efforts)effort.append(new Option(e,e));effort.value=values.effort||'medium';for(const element of [model,effort]){const cell=document.createElement('td');cell.append(element);row.append(cell);} $('roles').append(row);}invalidate();}
async function settings(){config=await api('/api/settings');token=config.csrf_token;$('destination').textContent=config.target;$('concurrency').value=config.concurrency;$('preset').replaceChildren();for(const p of Object.keys(config.presets))$('preset').append(new Option(p,p));$('preset').value=config.installed?'custom':'focused';fillRoles(Object.fromEntries(Object.entries(config.roles).map(([r,v])=>[r,v.model?v:config.presets.focused[r]])));$('restore').disabled=!config.restore_available;}
$('preset').addEventListener('change',()=>fillRoles(config.presets[$('preset').value]));$('settings-form').addEventListener('input',invalidate);
$('settings-form').addEventListener('submit',async event=>{event.preventDefault();try{const roles={};for(const row of $('roles').children)roles[row.dataset.role]={model:row.querySelector('input').value,effort:row.querySelector('select').value};const data=await api('/api/preview',{preset:$('preset').value,concurrency:Number($('concurrency').value),roles});previewId=data.preview_id;$('preview').replaceChildren(text('p',data.notice));for(const change of data.changes){$('preview').append(text('h3',change.path),text('pre',change.diff));}$('save').disabled=!data.can_save;status(data.can_save?'Önizleme hazır. Kaydet seçilen proje dosyalarını değiştirir.':'Çakışma: '+data.conflicts.join(', '),!data.can_save);}catch(error){invalidate();status(error.message,true);}});
$('save').addEventListener('click',async()=>{try{$('save').disabled=true;await api('/api/save',{preview_id:previewId});await settings();status('Kaydedildi. Yeni Codex oturumu açın.');}catch(e){status(e.message,true);}});
$('restore').addEventListener('click',async()=>{try{await api('/api/restore',{});await settings();$('preview').replaceChildren();status('Önceki konsol değişikliği geri yüklendi.');}catch(e){status(e.message,true);}});
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{for(const b of document.querySelectorAll('[data-tab]')){const active=b===button;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));$(b.dataset.tab).hidden=!active;}});
const count = value => value===undefined?'—':Number(value).toLocaleString('tr-TR');
function cells(row,values){for(const value of values)row.append(text('td',value));}
function options(id,values,empty){const select=$(id),value=select.value;select.replaceChildren(new Option(empty,''));for(const item of [...new Set(values)].sort())select.append(new Option(item,item));select.value=value;}
async function usage(refreshOptions=false){report=await api('/api/usage?'+new URLSearchParams(new FormData($('filters'))));$('metrics').replaceChildren();for(const [key,label] of [['input_tokens','Giriş'],['cached_input_tokens','Önbellek (giriş içinde)'],['output_tokens','Çıkış'],['total_tokens','Toplam']]){const box=text('div',label);box.className='metric';box.append(text('strong',count(report.totals[key])));$('metrics').append(box);} $('source').textContent=`Kaynak: ${report.source} · Durum: ${report.status} · ${report.records_observed} kayıt`; $('limits').textContent=report.limitations;$('groups').replaceChildren();for(const g of report.groups){const row=document.createElement('tr'),cell=document.createElement('td'),button=text('button',g.thread);button.addEventListener('click',()=>{$('detail-thread').value=g.thread;details();document.querySelector('[data-tab="details"]').click();});cell.append(button);row.append(cell);cells(row,[g.project,g.model+' / '+g.role,...['input_tokens','cached_input_tokens','output_tokens','total_tokens'].map(k=>count(g.usage[k]))]);$('groups').append(row);}if(refreshOptions){options('project-filter',report.groups.map(g=>g.project),'Tümü');options('thread-filter',report.groups.map(g=>g.thread),'Tümü');}options('detail-thread',report.groups.map(g=>g.thread),'Bir thread seçin');details();}
function details(){const selected=$('detail-thread').value,records=report.records.filter(r=>r.thread===selected);$('records').replaceChildren();$('detail-summary').replaceChildren(text('p',selected?`${selected} · ${records.length} gözlenen kayıt · Görev durumu: kullanılamıyor`:'Henüz bir thread seçilmedi.'));for(const record of records){const row=document.createElement('tr');cells(row,[record.timestamp,record.model+' / '+record.role,record.semantics,...['input_tokens','cached_input_tokens','output_tokens','total_tokens'].map(k=>count(record.usage[k]))]);$('records').append(row);}}
$('filters').addEventListener('submit',event=>{event.preventDefault();usage().catch(e=>status(e.message,true));});$('detail-thread').addEventListener('change',details);
(async()=>{try{await settings();await usage(true);status('Yerel konsol hazır. Ayarlar yalnızca Kaydet ile yazılır.');}catch(e){status(e.message,true);}})();
